/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'flow' : bigint,
  'tips' : string,
  'feedback' : string,
  'score' : bigint,
  'response' : string,
  'questionId' : bigint,
  'confidence' : bigint,
  'pacing' : bigint,
}
export type Category = { 'Technical' : null } |
  { 'Situational' : null } |
  { 'Behavioral' : null };
export interface Question {
  'id' : bigint,
  'text' : string,
  'category' : Category,
}
export interface Session {
  'id' : bigint,
  'startTime' : [] | [Time],
  'endTime' : [] | [Time],
  'answers' : Array<Answer>,
  'isActive' : boolean,
  'questions' : Array<bigint>,
}
export type Time = bigint;
export interface _SERVICE {
  'completeSession' : ActorMethod<[bigint], undefined>,
  'countQuestionsByCategory' : ActorMethod<[Category], bigint>,
  'createSession' : ActorMethod<[], bigint>,
  'fetchAllQuestions' : ActorMethod<[], Array<Question>>,
  'fetchAllSessions' : ActorMethod<[], Array<Session>>,
  'fetchQuestion' : ActorMethod<[bigint], [] | [Question]>,
  'findUpcomingQuestionId' : ActorMethod<[Category], bigint>,
  'getQuestionsByCategory' : ActorMethod<[Category], Array<bigint>>,
  'getSession' : ActorMethod<[bigint], [] | [Session]>,
  'setUserName' : ActorMethod<[string], undefined>,
  'startSession' : ActorMethod<[bigint], undefined>,
  'submitAnswer' : ActorMethod<[bigint, Answer], undefined>,
  'upsertQuestion' : ActorMethod<[Question], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];