/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Technical' : IDL.Null,
  'Situational' : IDL.Null,
  'Behavioral' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'category' : Category,
});
export const Time = IDL.Int;
export const Answer = IDL.Record({
  'flow' : IDL.Int,
  'tips' : IDL.Text,
  'feedback' : IDL.Text,
  'score' : IDL.Int,
  'response' : IDL.Text,
  'questionId' : IDL.Nat,
  'confidence' : IDL.Int,
  'pacing' : IDL.Int,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Opt(Time),
  'endTime' : IDL.Opt(Time),
  'answers' : IDL.Vec(Answer),
  'isActive' : IDL.Bool,
  'questions' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'completeSession' : IDL.Func([IDL.Nat], [], []),
  'countQuestionsByCategory' : IDL.Func([Category], [IDL.Nat], ['query']),
  'createSession' : IDL.Func([], [IDL.Nat], []),
  'fetchAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'fetchAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'fetchQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
  'findUpcomingQuestionId' : IDL.Func([Category], [IDL.Nat], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
  'setUserName' : IDL.Func([IDL.Text], [], []),
  'startSession' : IDL.Func([IDL.Nat], [], []),
  'submitAnswer' : IDL.Func([IDL.Nat, Answer], [], []),
  'upsertQuestion' : IDL.Func([Question], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Technical' : IDL.Null,
    'Situational' : IDL.Null,
    'Behavioral' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'category' : Category,
  });
  const Time = IDL.Int;
  const Answer = IDL.Record({
    'flow' : IDL.Int,
    'tips' : IDL.Text,
    'feedback' : IDL.Text,
    'score' : IDL.Int,
    'response' : IDL.Text,
    'questionId' : IDL.Nat,
    'confidence' : IDL.Int,
    'pacing' : IDL.Int,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Opt(Time),
    'endTime' : IDL.Opt(Time),
    'answers' : IDL.Vec(Answer),
    'isActive' : IDL.Bool,
    'questions' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'completeSession' : IDL.Func([IDL.Nat], [], []),
    'countQuestionsByCategory' : IDL.Func([Category], [IDL.Nat], ['query']),
    'createSession' : IDL.Func([], [IDL.Nat], []),
    'fetchAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'fetchAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'fetchQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
    'findUpcomingQuestionId' : IDL.Func([Category], [IDL.Nat], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
    'setUserName' : IDL.Func([IDL.Text], [], []),
    'startSession' : IDL.Func([IDL.Nat], [], []),
    'submitAnswer' : IDL.Func([IDL.Nat, Answer], [], []),
    'upsertQuestion' : IDL.Func([Question], [], []),
  });
};

export const init = ({ IDL }) => { return []; };