/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Answer {
    flow: bigint;
    tips: string;
    feedback: string;
    score: bigint;
    response: string;
    questionId: bigint;
    confidence: bigint;
    pacing: bigint;
}
export interface Session {
    id: bigint;
    startTime?: Time;
    endTime?: Time;
    answers: Array<Answer>;
    isActive: boolean;
    questions: Array<bigint>;
}
export interface Question {
    id: bigint;
    text: string;
    category: Category;
}
export type Time = bigint;
export enum Category {
    Technical = "Technical",
    Situational = "Situational",
    Behavioral = "Behavioral"
}
export interface backendInterface {
    completeSession(id: bigint): Promise<void>;
    countQuestionsByCategory(category: Category): Promise<bigint>;
    createSession(): Promise<bigint>;
    fetchAllQuestions(): Promise<Array<Question>>;
    fetchAllSessions(): Promise<Array<Session>>;
    fetchQuestion(id: bigint): Promise<Question | null>;
    findUpcomingQuestionId(category: Category): Promise<bigint>;
    getQuestionsByCategory(category: Category): Promise<Array<bigint>>;
    getSession(id: bigint): Promise<Session | null>;
    setUserName(name: string): Promise<void>;
    startSession(id: bigint): Promise<void>;
    submitAnswer(sessionId: bigint, answer: Answer): Promise<void>;
    upsertQuestion(question: Question): Promise<void>;
}
import type { Answer as _Answer, Category as _Category, Question as _Question, Session as _Session, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSession(arg0);
            return result;
        }
    }
    async countQuestionsByCategory(arg0: Category): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countQuestionsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countQuestionsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSession(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession();
            return result;
        }
    }
    async fetchAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAllQuestions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAllQuestions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAllSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAllSessions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAllSessions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchQuestion(arg0: bigint): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchQuestion(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchQuestion(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async findUpcomingQuestionId(arg0: Category): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.findUpcomingQuestionId(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUpcomingQuestionId(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getQuestionsByCategory(arg0: Category): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getSession(arg0: bigint): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserName(arg0);
            return result;
        }
    }
    async startSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0);
            return result;
        }
    }
    async submitAnswer(arg0: bigint, arg1: Answer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return result;
        }
    }
    async upsertQuestion(arg0: Question): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertQuestion(to_candid_Question_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertQuestion(to_candid_Question_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Question | null {
    return value.length === 0 ? null : from_candid_Question_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: [] | [_Time];
    endTime: [] | [_Time];
    answers: Array<_Answer>;
    isActive: boolean;
    questions: Array<bigint>;
}): {
    id: bigint;
    startTime?: Time;
    endTime?: Time;
    answers: Array<Answer>;
    isActive: boolean;
    questions: Array<bigint>;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.startTime)),
        endTime: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.endTime)),
        answers: value.answers,
        isActive: value.isActive,
        questions: value.questions
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    category: _Category;
}): {
    id: bigint;
    text: string;
    category: Category;
} {
    return {
        id: value.id,
        text: value.text,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Technical: null;
} | {
    Situational: null;
} | {
    Behavioral: null;
}): Category {
    return "Technical" in value ? Category.Technical : "Situational" in value ? Category.Situational : "Behavioral" in value ? Category.Behavioral : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    category: Category;
}): {
    id: bigint;
    text: string;
    category: _Category;
} {
    return {
        id: value.id,
        text: value.text,
        category: to_candid_Category_n1(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Technical: null;
} | {
    Situational: null;
} | {
    Behavioral: null;
} {
    return value == Category.Technical ? {
        Technical: null
    } : value == Category.Situational ? {
        Situational: null
    } : value == Category.Behavioral ? {
        Behavioral: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
